### Get all groups
GET http://localhost:3001/api/groups

### Create a group
POST http://localhost:3001/api/groups
Content-Type: application/json

{
  "group_name": "team awesome"
}

### Get all students
GET http://localhost:3001/api/students

### Add a student to a group
POST http://localhost:3001/api/students
Content-Type: application/json

{
  "group_id": "62fd0cebc99ea7d38e632e4d",
  "first": "James",
  "last": "Buchmann"
}

### Get a student by id
GET http://localhost:3001/api/student?student_id=62fc2795cd742677be8e54d1&group_id=62fbe4f36af676e06648408d

### Delete a student by id
DELETE http://localhost:3001/api/student?student_id=62fbb62c46994413d50f578f&group_id=62fab3ae7195131226d24df2