GET http://localhost:3001/api/groups

###

POST http://localhost:3001/api/groups
Content-Type: application/json

{
  "group_name": "team awesome"
}

###

POST http://localhost:3001/api/students/
Content-Type: application/json

{
  "group_id": "62fab3ae7195131226d24df2",
  "name": "gunner"
}

###

DELETE http://localhost:3001/api/students/
Content-Type: application/json

{
  "group_id": "62fab3ae7195131226d24df2",
  "student_id": "62fab3e07195131226d24df5"
}